### Create new article
Post http://localhost:3000/articles
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M


{
    "article": {
        "title": "How to train your dragon",
        "description": "Ever wonder how",
        "body": "you have to body",
        "tagList": ["dog","bird","cat"]
    }
} 


### get article by slug
Get http://localhost:3000/articles/how-to-train-your-dragon-xi7hh3
content-Type: application/json


### delete article by slug
Delete http://localhost:3000/articles/how-to-train-your-dragon-wkhbfl
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M


{
    "article": {
        "title": "How to train your dragon",
        "description": "Ever wonder how",
        "body": "you have to body",
        "tagList": []
    }
} 

### update article by slug
Put http://localhost:3000/articles/how-to-train-your-dragon-wkhbfl
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M


{
    "article": {
        "title": "new title 9s here"
    }
} 


### Get all articles
Get http://localhost:3000/articles
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M


### Get all articles by limit and offset
Get http://localhost:3000/articles?limit=2&offset=0
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M


### Get all articles by tags
Get http://localhost:3000/articles?tag=bird
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M


### Get all articles by username
Get http://localhost:3000/articles?author=foo
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M



### add favorite article to user array 
Post http://localhost:3000/articles/how-to-train-your-dragon-i9zmoq/favorite
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M
 

### delete favorite article from user array 
DELETE http://localhost:3000/articles/how-to-train-your-dragon-i9zmoq/favorite
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M
 

### get favorite user article 
Get http://localhost:3000/articles?favorited=foo
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTU0NDV9.bURl1omRTMWNgWhXMJ_LT24chSNX_z2ny-gro3ALU2M
 
 