### Get all tags
GET http://localhost:3000/tags  

### Get one user
GET http://localhost:3000/users/me
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTgyODJ9.n4TyrEm5_bdNrIzrR9pMdLoLfr9ETRjnL1Gm0cjt3VA


### Create new user
Post http://localhost:3000/users
content-Type: application/json

{
    "user": {
        "username": "foo2",
        "email": "foo2@gmail.com",
        "password": "123"
    }
} 

### Login User
Post http://localhost:3000/users/login
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTgyODJ9.n4TyrEm5_bdNrIzrR9pMdLoLfr9ETRjnL1Gm0cjt3VA

{
    "user": {
        "email": "foo@gmail.com",
        "password": "123"
    }
} 


### update user
PUT http://localhost:3000/users
content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmb28iLCJlbWFpbCI6ImZvb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTgyODJ9.n4TyrEm5_bdNrIzrR9pMdLoLfr9ETRjnL1Gm0cjt3VA

{
    "user": {
        "bio": "this is my new bio"
    }
}